### PR TITLE
Fix CI to ensure requirements are installed.

### PR DESCRIPTION
**Pull request by joehandzik**
Signed-Off-By: Joe Handzik <jhandzik@nvidia.com>

### CODE REVIEW

**Comment by roclark** [comment]
Hmm... this is odd. That technically shouldn't be necessary as the dependencies are installed a few steps down as we install the package with pip. That makes me feel that one of the dependencies we are using had an update and no longer lists a sub-dependency that it requires in their packaging since this worked fine yesterday. I'm comparing the output of a job that succeeded yesterday with the failed job from today to see if there are any differences.

**Comment by joehandzik** [comment]
Gotcha - yeah, this was a guess, but I started looking at older jobs and noticed six was already present in the wheel. Do we just need to specify six in the wheel then instead, or something to that effect?

**Comment by roclark** [comment]
Yeah, that would be our workaround to get the CI working again. Looks like websocket-client (a dependency of Docker) was updated last night and no longer has `six` as a dependency which got us into this mess. I think adding `six` to setup.py is the fix here, but those dependencies need to be fixed (nothing we can do about that).

**Comment by joehandzik** [comment]
I created #78 as an alt-fix - if that works and passes CI, we can merge that and throw this away. If that doesn't solve the problem on its own, I'll rebase here and fix the failed requirement in the test phase too.

**Comment by joehandzik** [comment]
High confidence in #78 - closing this.

**Pull request closed without merging**
